# Sample .travis.yml for R projects

# Enable installation
sudo: true

# Use R
language: r
warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  ## For installing all CRAN dependencies using DESCRIPTION
  - ./travis-tool.sh install_deps

  ## For installing all Bioconductor dependencies using DESCRIPTION
  - ./travis-tool.sh install_bioc_deps

env:
  global:
    - BIOC_USE_DEVEL="FALSE"  ## Use the current release version
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"  ## do not build vignettes or manual
    - _R_CHECK_TIMINGS_="0"  ## get the timing information for the examples for all of your functions

script:
  - travis_wait ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

## Check how much time was spent in each of the example pages
after_script:
  - ./travis-tool.sh dump_logs_by_extension "timings"
  - ./travis-tool.sh dump_sysinfo

## CodeCov
r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'library(covr); coveralls()'
